//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace YJ.AppLink.Api {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendResponse {
        
        private bool successField;
        
        private string errorField;
        
        private string requestIdField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KeyValue {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessage {
        
        private string messageField;
        
        private string handleField;
        
        private bool sendFromDeskField;
        
        private bool sendFromDeskFieldSpecified;
        
        private string sendModeField;
        
        private string requestIdField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        public bool SendFromDesk {
            get {
                return this.sendFromDeskField;
            }
            set {
                this.sendFromDeskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendFromDeskSpecified {
            get {
                return this.sendFromDeskFieldSpecified;
            }
            set {
                this.sendFromDeskFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SendMode {
            get {
                return this.sendModeField;
            }
            set {
                this.sendModeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOrder {
        
        private string marketIdField;
        
        private double bidField;
        
        private bool bidFieldSpecified;
        
        private int bidSizeField;
        
        private bool bidSizeFieldSpecified;
        
        private double askField;
        
        private bool askFieldSpecified;
        
        private int askSizeField;
        
        private bool askSizeFieldSpecified;
        
        private string colorField;
        
        private string handleField;
        
        private bool sendFromDeskField;
        
        private bool sendFromDeskFieldSpecified;
        
        private string sendModeField;
        
        private string requestIdField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string MarketId {
            get {
                return this.marketIdField;
            }
            set {
                this.marketIdField = value;
            }
        }
        
        /// <remarks/>
        public double Bid {
            get {
                return this.bidField;
            }
            set {
                this.bidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BidSpecified {
            get {
                return this.bidFieldSpecified;
            }
            set {
                this.bidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int BidSize {
            get {
                return this.bidSizeField;
            }
            set {
                this.bidSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BidSizeSpecified {
            get {
                return this.bidSizeFieldSpecified;
            }
            set {
                this.bidSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Ask {
            get {
                return this.askField;
            }
            set {
                this.askField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AskSpecified {
            get {
                return this.askFieldSpecified;
            }
            set {
                this.askFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int AskSize {
            get {
                return this.askSizeField;
            }
            set {
                this.askSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AskSizeSpecified {
            get {
                return this.askSizeFieldSpecified;
            }
            set {
                this.askSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string Handle {
            get {
                return this.handleField;
            }
            set {
                this.handleField = value;
            }
        }
        
        /// <remarks/>
        public bool SendFromDesk {
            get {
                return this.sendFromDeskField;
            }
            set {
                this.sendFromDeskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendFromDeskSpecified {
            get {
                return this.sendFromDeskFieldSpecified;
            }
            set {
                this.sendFromDeskFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SendMode {
            get {
                return this.sendModeField;
            }
            set {
                this.sendModeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LegValues {
        
        private string legIdField;
        
        private double theoreticalPriceField;
        
        private bool theoreticalPriceFieldSpecified;
        
        private double gammaField;
        
        private bool gammaFieldSpecified;
        
        private double deltaField;
        
        private bool deltaFieldSpecified;
        
        private double vegaField;
        
        private bool vegaFieldSpecified;
        
        private double thetaField;
        
        private bool thetaFieldSpecified;
        
        private double rhoField;
        
        private bool rhoFieldSpecified;
        
        private double volField;
        
        private bool volFieldSpecified;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string LegId {
            get {
                return this.legIdField;
            }
            set {
                this.legIdField = value;
            }
        }
        
        /// <remarks/>
        public double TheoreticalPrice {
            get {
                return this.theoreticalPriceField;
            }
            set {
                this.theoreticalPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TheoreticalPriceSpecified {
            get {
                return this.theoreticalPriceFieldSpecified;
            }
            set {
                this.theoreticalPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Gamma {
            get {
                return this.gammaField;
            }
            set {
                this.gammaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GammaSpecified {
            get {
                return this.gammaFieldSpecified;
            }
            set {
                this.gammaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeltaSpecified {
            get {
                return this.deltaFieldSpecified;
            }
            set {
                this.deltaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Vega {
            get {
                return this.vegaField;
            }
            set {
                this.vegaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VegaSpecified {
            get {
                return this.vegaFieldSpecified;
            }
            set {
                this.vegaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Theta {
            get {
                return this.thetaField;
            }
            set {
                this.thetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThetaSpecified {
            get {
                return this.thetaFieldSpecified;
            }
            set {
                this.thetaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Rho {
            get {
                return this.rhoField;
            }
            set {
                this.rhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RhoSpecified {
            get {
                return this.rhoFieldSpecified;
            }
            set {
                this.rhoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Vol {
            get {
                return this.volField;
            }
            set {
                this.volField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolSpecified {
            get {
                return this.volFieldSpecified;
            }
            set {
                this.volFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PriceResponse {
        
        private string marketDetailIdField;
        
        private double theoreticalOverrideField;
        
        private bool theoreticalOverrideFieldSpecified;
        
        private double bestImpliedVolField;
        
        private bool bestImpliedVolFieldSpecified;
        
        private double lastImpliedVolField;
        
        private bool lastImpliedVolFieldSpecified;
        
        private LegValues[] legValuesField;
        
        private KeyValue[] keyValuesField;
        
        private double volatilityScalingNumberField;
        
        private bool volatilityScalingNumberFieldSpecified;
        
        /// <remarks/>
        public string MarketDetailId {
            get {
                return this.marketDetailIdField;
            }
            set {
                this.marketDetailIdField = value;
            }
        }
        
        /// <remarks/>
        public double TheoreticalOverride {
            get {
                return this.theoreticalOverrideField;
            }
            set {
                this.theoreticalOverrideField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TheoreticalOverrideSpecified {
            get {
                return this.theoreticalOverrideFieldSpecified;
            }
            set {
                this.theoreticalOverrideFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double BestImpliedVol {
            get {
                return this.bestImpliedVolField;
            }
            set {
                this.bestImpliedVolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BestImpliedVolSpecified {
            get {
                return this.bestImpliedVolFieldSpecified;
            }
            set {
                this.bestImpliedVolFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double LastImpliedVol {
            get {
                return this.lastImpliedVolField;
            }
            set {
                this.lastImpliedVolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastImpliedVolSpecified {
            get {
                return this.lastImpliedVolFieldSpecified;
            }
            set {
                this.lastImpliedVolFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegValues")]
        public LegValues[] LegValues {
            get {
                return this.legValuesField;
            }
            set {
                this.legValuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
        
        /// <remarks/>
        public double VolatilityScalingNumber {
            get {
                return this.volatilityScalingNumberField;
            }
            set {
                this.volatilityScalingNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolatilityScalingNumberSpecified {
            get {
                return this.volatilityScalingNumberFieldSpecified;
            }
            set {
                this.volatilityScalingNumberFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OptionLeg {
        
        private string optionTypeField;
        
        private string legIdField;
        
        private string exerciseTypeField;
        
        private string styleField;
        
        private string descriptionField;
        
        private string termField;
        
        private string strikeTypeField;
        
        private double strikeField;
        
        private double ratioField;
        
        private int directionField;
        
        private Underlying underlyingField;
        
        private string oSICodeField;
        
        private string crossIdField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string OptionType {
            get {
                return this.optionTypeField;
            }
            set {
                this.optionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LegId {
            get {
                return this.legIdField;
            }
            set {
                this.legIdField = value;
            }
        }
        
        /// <remarks/>
        public string ExerciseType {
            get {
                return this.exerciseTypeField;
            }
            set {
                this.exerciseTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
            }
        }
        
        /// <remarks/>
        public string StrikeType {
            get {
                return this.strikeTypeField;
            }
            set {
                this.strikeTypeField = value;
            }
        }
        
        /// <remarks/>
        public double Strike {
            get {
                return this.strikeField;
            }
            set {
                this.strikeField = value;
            }
        }
        
        /// <remarks/>
        public double Ratio {
            get {
                return this.ratioField;
            }
            set {
                this.ratioField = value;
            }
        }
        
        /// <remarks/>
        public int Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public Underlying Underlying {
            get {
                return this.underlyingField;
            }
            set {
                this.underlyingField = value;
            }
        }
        
        /// <remarks/>
        public string OSICode {
            get {
                return this.oSICodeField;
            }
            set {
                this.oSICodeField = value;
            }
        }
        
        /// <remarks/>
        public string CrossId {
            get {
                return this.crossIdField;
            }
            set {
                this.crossIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Underlying {
        
        private string symbolField;
        
        private string nameField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SwapLeg {
        
        private string swapTypeField;
        
        private string legIdField;
        
        private string descriptionField;
        
        private Underlying underlyingField;
        
        private int directionField;
        
        private string termField;
        
        private double ratioField;
        
        private double referencePriceField;
        
        private bool referencePriceFieldSpecified;
        
        private double referenceDeltaField;
        
        private bool referenceDeltaFieldSpecified;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string SwapType {
            get {
                return this.swapTypeField;
            }
            set {
                this.swapTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LegId {
            get {
                return this.legIdField;
            }
            set {
                this.legIdField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public Underlying Underlying {
            get {
                return this.underlyingField;
            }
            set {
                this.underlyingField = value;
            }
        }
        
        /// <remarks/>
        public int Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public string Term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
            }
        }
        
        /// <remarks/>
        public double Ratio {
            get {
                return this.ratioField;
            }
            set {
                this.ratioField = value;
            }
        }
        
        /// <remarks/>
        public double ReferencePrice {
            get {
                return this.referencePriceField;
            }
            set {
                this.referencePriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferencePriceSpecified {
            get {
                return this.referencePriceFieldSpecified;
            }
            set {
                this.referencePriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double ReferenceDelta {
            get {
                return this.referenceDeltaField;
            }
            set {
                this.referenceDeltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceDeltaSpecified {
            get {
                return this.referenceDeltaFieldSpecified;
            }
            set {
                this.referenceDeltaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StockLeg {
        
        private string legIdField;
        
        private string descriptionField;
        
        private int directionField;
        
        private Underlying underlyingField;
        
        private double ratioField;
        
        private bool ratioFieldSpecified;
        
        private double priceField;
        
        private bool priceFieldSpecified;
        
        private string crossIdField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string LegId {
            get {
                return this.legIdField;
            }
            set {
                this.legIdField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public Underlying Underlying {
            get {
                return this.underlyingField;
            }
            set {
                this.underlyingField = value;
            }
        }
        
        /// <remarks/>
        public double Ratio {
            get {
                return this.ratioField;
            }
            set {
                this.ratioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RatioSpecified {
            get {
                return this.ratioFieldSpecified;
            }
            set {
                this.ratioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CrossId {
            get {
                return this.crossIdField;
            }
            set {
                this.crossIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Participant {
        
        private string nameField;
        
        private string typeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Quote {
        
        private string idField;
        
        private Participant senderField;
        
        private Participant receiverField;
        
        private string sentOrReceivedField;
        
        private double bidField;
        
        private bool bidFieldSpecified;
        
        private double askField;
        
        private bool askFieldSpecified;

        private System.DateTime quoteTimeField;
        
        private bool quoteTimeFieldSpecified;
        
        private int bidSizeField;
        
        private bool bidSizeFieldSpecified;
        
        private int askSizeField;
        
        private bool askSizeFieldSpecified;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public Participant Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        public Participant Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public string SentOrReceived {
            get {
                return this.sentOrReceivedField;
            }
            set {
                this.sentOrReceivedField = value;
            }
        }
        
        /// <remarks/>
        public double Bid {
            get {
                return this.bidField;
            }
            set {
                this.bidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BidSpecified {
            get {
                return this.bidFieldSpecified;
            }
            set {
                this.bidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Ask {
            get {
                return this.askField;
            }
            set {
                this.askField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AskSpecified {
            get {
                return this.askFieldSpecified;
            }
            set {
                this.askFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime QuoteTime {
            get {
                return this.quoteTimeField;
            }
            set {
                this.quoteTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuoteTimeSpecified {
            get {
                return this.quoteTimeFieldSpecified;
            }
            set {
                this.quoteTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int BidSize {
            get {
                return this.bidSizeField;
            }
            set {
                this.bidSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BidSizeSpecified {
            get {
                return this.bidSizeFieldSpecified;
            }
            set {
                this.bidSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int AskSize {
            get {
                return this.askSizeField;
            }
            set {
                this.askSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AskSizeSpecified {
            get {
                return this.askSizeFieldSpecified;
            }
            set {
                this.askSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarketDetail {
        
        private string idField;
        
        private string descriptionField;
        
        private string strategyField;
        
        private Quote bestBidField;
        
        private Quote bestAskField;

        private Quote bidSizeField;
        
        private Quote lastQuoteField;
        
        private double lastTradeField;
        
        private bool lastTradeFieldSpecified;
        
        private System.DateTime lastTradeTimeField;
        
        private bool lastTradeTimeFieldSpecified;
        
        private StockLeg[] stockLegsField;
        
        private SwapLeg[] swapLegsField;
        
        private OptionLeg[] optionLegsField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Strategy {
            get {
                return this.strategyField;
            }
            set {
                this.strategyField = value;
            }
        }
        
        /// <remarks/>
        public Quote BestBid {
            get {
                return this.bestBidField;
            }
            set {
                this.bestBidField = value;
            }
        }
        
        /// <remarks/>
        public Quote BestAsk {
            get {
                return this.bestAskField;
            }
            set {
                this.bestAskField = value;
            }
        }

        /// <remarks/>
        public Quote BidSize
        {
            get
            {
                return this.bidSizeField;
            }
            set
            {
                this.bidSizeField = value;
            }
        }

        /// <remarks/>
        public Quote LastQuote {
            get {
                return this.lastQuoteField;
            }
            set {
                this.lastQuoteField = value;
            }
        }
        
        /// <remarks/>
        public double LastTrade {
            get {
                return this.lastTradeField;
            }
            set {
                this.lastTradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastTradeSpecified {
            get {
                return this.lastTradeFieldSpecified;
            }
            set {
                this.lastTradeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastTradeTime {
            get {
                return this.lastTradeTimeField;
            }
            set {
                this.lastTradeTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastTradeTimeSpecified {
            get {
                return this.lastTradeTimeFieldSpecified;
            }
            set {
                this.lastTradeTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StockLegs")]
        public StockLeg[] StockLegs {
            get {
                return this.stockLegsField;
            }
            set {
                this.stockLegsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SwapLegs")]
        public SwapLeg[] SwapLegs {
            get {
                return this.swapLegsField;
            }
            set {
                this.swapLegsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OptionLegs")]
        public OptionLeg[] OptionLegs {
            get {
                return this.optionLegsField;
            }
            set {
                this.optionLegsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PriceUpdate {
        
        private string actionField;
        
        private string userField;
        
        private string marketDetailIdField;
        
        private MarketDetail marketDetailField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string MarketDetailId {
            get {
                return this.marketDetailIdField;
            }
            set {
                this.marketDetailIdField = value;
            }
        }
        
        /// <remarks/>
        public MarketDetail MarketDetail {
            get {
                return this.marketDetailField;
            }
            set {
                this.marketDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StopServiceRequest {
        
        private string serviceField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartServiceRequest {
        
        private string versionField;
        
        private string serviceField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Envelope {
        
        private object contentField;
        
        private KeyValue[] keyValuesField;
        
        /// <remarks/>
        public object Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyValues")]
        public KeyValue[] KeyValues {
            get {
                return this.keyValuesField;
            }
            set {
                this.keyValuesField = value;
            }
        }
    }
}
